=== innovaphone/php-update-server/full-config.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/full-config.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE config SYSTEM "full-config.dtd">

    <config>
    ...
    </config>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT config (classes|master|fwstorage|backup|status|times|phases|queries|environments|nobootdev|nofirmdev|customcerts|stdargs)*>
<!ATTLIST config
    debugmerge CDATA #IMPLIED
    debugcerts CDATA #IMPLIED
    debugscript CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT master (applies)*>
<!ATTLIST master
    info CDATA #IMPLIED
    expire CDATA #IMPLIED
    cache CDATA #IMPLIED
    user CDATA #IMPLIED
    password CDATA #IMPLIED
    firmware CDATA #IMPLIED
    bootcode CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT applies (#PCDATA)>
<!ATTLIST applies
    env CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT fwstorage EMPTY>
<!ATTLIST fwstorage
    url CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT backup EMPTY>
<!ATTLIST backup
    dir CDATA #IMPLIED
    nbackups CDATA #IMPLIED
    scfg CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT status EMPTY>
<!ATTLIST status
    dir CDATA #IMPLIED
    missing CDATA #IMPLIED
    refresh CDATA #IMPLIED
    expire CDATA #IMPLIED
    logkeep CDATA #IMPLIED
    usehttpsdevlinks CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT times EMPTY>
<!ATTLIST times
    initial CDATA #IMPLIED
    dir CDATA #IMPLIED
    allow CDATA #IMPLIED
    check CDATA #IMPLIED
    polling CDATA #IMPLIED
    forcestaging CDATA #IMPLIED
    interval CDATA #IMPLIED
    grace CDATA #IMPLIED
    forcehttps CDATA #IMPLIED
    httpsport CDATA #IMPLIED
    forcetrust CDATA #IMPLIED
    httpsurlmod CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT phases (phase)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT phase EMPTY>
<!ATTLIST phase
    id CDATA #IMPLIED
    seq CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT environments (environment)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT environment (implies)*>
<!ATTLIST environment
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT implies (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT classes (class)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT class (model)*>
<!ATTLIST class
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT model (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nobootdev (model)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nofirmdev (model)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT customcerts EMPTY>
<!ATTLIST customcerts
    CAtype CDATA #IMPLIED
    dir CDATA #IMPLIED
    CAkeys CDATA #IMPLIED
    CAuser CDATA #IMPLIED
    renew CDATA #IMPLIED
    CSRsignature CDATA #IMPLIED
    CSRdn-st CDATA #IMPLIED
    CSRsan-dns-3 CDATA #IMPLIED
    CApassword CDATA #IMPLIED
    CSRdn-ou CDATA #IMPLIED
    CAurl CDATA #IMPLIED
    CSRdn-l CDATA #IMPLIED
    CSRsan-ip-2 CDATA #IMPLIED
    network CDATA #IMPLIED
    CSRdn-o CDATA #IMPLIED
    auto-sign-off CDATA #IMPLIED
    CSRsan-dns-1 CDATA #IMPLIED
    CAname CDATA #IMPLIED
    netmask CDATA #IMPLIED
    CAnamesep CDATA #IMPLIED
    CSRsan-ip-1 CDATA #IMPLIED
    CAwildcard CDATA #IMPLIED
    CSRkey CDATA #IMPLIED
    CSRsan-dns-2 CDATA #IMPLIED
    CSRdn-c CDATA #IMPLIED
    CSRdn-cn CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT stdargs (stdarg)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT stdarg EMPTY>
<!ATTLIST stdarg
    key CDATA #IMPLIED
    value CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT queries (query)*>
<!ATTLIST queries
    scfg CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT query (cmd|applies|show)*>
<!ATTLIST query
    id CDATA #IMPLIED
    title CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cmd (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT show (#PCDATA)>
<!ATTLIST show
    title CDATA #IMPLIED
  >

=== innovaphone/php-update-server/full-config.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE config SYSTEM "full-config.dtd">

<!--
this is a pseudo config file that includes all tgs and all attributes at löeast one.  Used to generate .dtd file.
DO NOT use for production!
-->

<config debugmerge="false" debugcerts="false" debugscript="false">
    
    <master 
        info=""
        expire=""
        cache=""/>
    
    <fwstorage url=""/>
    
    <backup 
        dir=""
        nbackups=""
        scfg=""
    />
    
    <status
        dir=""
        missing="" 
        refresh=""
        expire="" 
        logkeep=""
        usehttpsdevlinks=""
    />
 
    <times 
        dir=""
        allow=""
        initial=""
        check=""
        polling=""
        interval=""
        grace=""
        forcehttps=""
        httpsport=""
        forcetrust=""
        httpsurlmod=""
    />
    
    <phases>
        <phase id="" seq=""/>
        <phase id="" seq=""/>
    </phases>
    
    <environments>
        <environment id=''>
            <implies>default</implies>
        </environment>
        <environment id=''>
            <implies>default</implies>
        </environment>
    </environments>

    <classes>
        <class id="">
            <model>name</model>
        </class>
        <class id="">
            <model>name</model>
        </class>
    </classes>
    
    <nobootdev>
        <model>name1</model>
        <model>name2</model>
    </nobootdev>

    <nofirmdev>
        <model>name1</model>
        <model>name2</model>
    </nofirmdev>
        
    <customcerts
        dir="certs"
        CAkeys=""
        CAtype=""
        CAuser=""
        CApassword="" 
        CAurl=""
        CAname=""
        CAnamesep=""
        CAwildcard=""
        
        CSRdn-c=""
        CSRdn-cn=""
        CSRdn-l=""
        CSRdn-o=""
        CSRdn-ou=""
        CSRdn-st=""
        CSRkey=""
        CSRsan-dns-1=""
        CSRsan-dns-2=""
        CSRsan-dns-3=""
        CSRsan-ip-1=""
        CSRsan-ip-2=""
        CSRsignature=""

        renew=""
        auto-sign-off=""
        network=""
        netmask=""
    />

    <stdargs>
        <stdarg key="" value=""/>
        <stdarg key="" value=""/>
    </stdargs>

    <queries
        scfg=""
    >
        <query id="" title="">
            <cmd>cmd</cmd>
            <applies>pattern</applies>
        </query>
        <query id="" title="">
            <cmd>cmd</cmd>
            <applies>pattern</applies>
            <show title="">command</show>
            <show title="">command</show>
        </query>
    </queries>
</config>

=== innovaphone/php-update-server/user-config-dvl.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE config SYSTEM "full-config.dtd">

<config debugmerge="false" debugcerts="true" debugscript="false">
    <master info="http://172.16.0.10/CMD0/box_info.xmly"/>
    <fwstorage xurl="http://webbuild.innovaphone.com/fw.php/build={build}&amp;model=#t/"/>
    <backup
        dir="backup"
    />
    <status
        dir="status"
        missing="200"
        refresh="9000"
    />
    
    <times 
        xallow="22,23,0,1,2,3,4" 
        initial="1"
        forcehttps="false"
        forcetrust="false"
        httpsport="444"
        httpsurlmod="/sample/pample/i"
        interval="15"
    />
    
    <customcerts
        dir="certs"
        CAkeys="CAkey*"
        CAtype="manual"
        CAuser="administrator"
        CApassword="password" 
        CAurl=""
        xCAname="innovaphone Device Certification Authority,innovaphone Device Certification Authority 2"
        CAname="innovaphone-INNO-DC-W2K8-Zertifizierungsserver"
        CAnamesep=","
        
        CSRkey="2048-bit"
        CSRsignature="SH256"
        CSRdn-cn="{hwid}"
        CSRdn-ou=""
        CSRdn-o=""
        CSRdn-l=""
        CSRdn-st=""
        CSRdn-c=""
        CSRsan-dns-1="{name}.company.com"
        CSRsan-dns-2="{hwid}.company.com"
        CSRsan-dns-3="{rdns}"
        CSRsan-ip-1="{realip}"
        CSRsan-ip-2=""

        renew="90"
        auto-sign-off="false"
        network="172.16.0.0"
        netmask="255.255.0.0"
        storekey="true"
    />
        
    <environments>
        <environment id='hq'>
            <implies>intranet</implies>
        </environment>
        <environment id='intranet'/>
        <environment id='homeoffice'/>
    </environments>
    <phases>
        <!-- sequence is important! -->
        <phase id="staging" seq="100"/>
    </phases>
    <queries>

        <!--
        <query id="admin">
            <applies>*</applies>
            <show title="Name">/state/queries/admin/info/@name</show>
        </query>
        <query id="media" title="Media">
            <cmd>mod cmd MEDIA xml-info</cmd>
            <applies>phone</applies>
            <show title="NAT">concat(/state/queries/media/info/nat/@result, ' (', /state/queries/media/info/nat/@public-addr, ')')</show>
            <show title="Server">concat('STUN: ', /state/queries/media/info/@stun, ' TURN: ', /state/queries/media/info/@turn, ' (', /state/queries/media/info/@turn-user, ')')</show>
        </query>
        -->
        <query id="certificates">
            <applies>*</applies>
            <show title="Subject">/state/queries/certificates/info/servercert/certificate/@subject_cn</show>
            <show title="Issuer">/state/queries/certificates/info/servercert/certificate/@issuer_cn</show>
        </query>

    </queries>
</config>
